CREATE TABLE goodgames_list (
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    game_id INTEGER,
    game_name TEXT not null, 
    game_url TEXT not null,
    playlist BOOLEAN,
    played BOOLEAN,
    favorite BOOLEAN,
    userid INTEGER REFERENCES goodgames_users(id)
)

